name: keep_screen_on
description: This plugin disables automatic screen off and prevents the screen from turning off.
version: 3.0.0
homepage: https://github.com/craftsoft-dev/flutter_keep_screen_on

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  keep_screen_on_platform_interface: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  plugin_platform_interface: ^2.1.6
  test: ^1.24.3

flutter:
  plugin:
    platforms:
      android:
        package: dev.craftsoft.keepscreenon
        pluginClass: KeepScreenOnPlugin
      ios:
        pluginClass: KeepScreenOnPlugin
