name: keep_screen_on_platform_interface
description: This plugin disables automatic screen off and prevents the screen from turning off.
version: 2.0.0+1
homepage: https://github.com/craftsoft-dev/flutter_keep_screen_on

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
